DATABASE_PATH = 'data/SolarData.sqlite3'
REGIONS_CSV_PATH = 'data/regions.csv'
LOCATIONS_CSV_PATH = 'data/locations.csv'
SOLAR_HOURS_CSV_PATH = 'data/solar_hours.csv'
RESIDENTIAL_SUMMER_RATES_CSV_PATH = 'data/residential_summer_rates.csv'
RESIDENTIAL_WINTER_RATES_CSV_PATH = 'data/residential_winter_rates.csv'
PDBT_RATE_CSV_PATH = 'data/pdbt_rate.csv'
